#!/usr/bin/env bash
# configures nginx server to return a header as response
sudo apt-get -y install nginx

sudo sed -i "23i \\\tadd_header X-Served-By \$hostname;" /etc/nginx/sites-available/default

sudo service nginx restart
