#!/usr/bin/env bash
#installs haproxy on a server and sets up roundrobin load balancing
sudo apt-get -y install --no-install-recommends software-properties-common
sudo add-apt-repository ppa:vbernat/haproxy-2.8 -y
sudo apt-get -y install haproxy=2.8.\*


echo -e "frontend web-frontend
\tbind *:80
\tmode http
\tdefault_backend web_backend
backend web_backend
\tmode http
\tbalance roundrobin
\toption forwardfor
\thttp-request set-header X-Forwarded-Port %[dst_port]
\tserver 337006-web-01 100.25.38.35:80 check
\tserver 337006-web-02 100.25.196.250:80 check" | sudo tee -a /etc/haproxy/haproxy.cfg

sudo service haproxy restart
