#!/usr/bin/env bash
#prints words over 10 iterations
#prints "bad luck" in 4th iteration
#prints "good luck" in 8th
#prints "Best School" for others
i=1
while ((i < 11))
do
	if ((i == 4))
	then
		echo "bad luck"
	elif ((i == 8))
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	((i++))
done
